/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class MenuCliente extends javax.swing.JFrame {

    /**
     * Creates new form MenuCliente
     */
    public MenuCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container1 = new javax.swing.JPanel();
        painel1 = new javax.swing.JDesktopPane();
        painel2 = new javax.swing.JDesktopPane();
        painel3 = new javax.swing.JDesktopPane();
        painel4 = new javax.swing.JDesktopPane();
        saqueBotao = new javax.swing.JButton();
        depositoBotao = new javax.swing.JButton();
        extBotao = new javax.swing.JButton();
        alteraBotao = new javax.swing.JButton();
        cancelaBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        saqueBotao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saqueBotao.setText("Saque");
        saqueBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saqueBotaoActionPerformed(evt);
            }
        });

        depositoBotao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        depositoBotao.setText("Deposito");
        depositoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositoBotaoActionPerformed(evt);
            }
        });

        extBotao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        extBotao.setText("Extrato");

        alteraBotao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alteraBotao.setText("Alterar senha");
        alteraBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alteraBotaoActionPerformed(evt);
            }
        });

        cancelaBotao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelaBotao.setText("Cancelar");
        cancelaBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaBotaoActionPerformed(evt);
            }
        });

        painel4.setLayer(saqueBotao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel4.setLayer(depositoBotao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel4.setLayer(extBotao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel4.setLayer(alteraBotao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel4.setLayer(cancelaBotao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painel4Layout = new javax.swing.GroupLayout(painel4);
        painel4.setLayout(painel4Layout);
        painel4Layout.setHorizontalGroup(
            painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel4Layout.createSequentialGroup()
                .addGroup(painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel4Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(alteraBotao))
                    .addGroup(painel4Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(saqueBotao)
                        .addGap(18, 18, 18)
                        .addComponent(depositoBotao)
                        .addGap(18, 18, 18)
                        .addComponent(extBotao))
                    .addGroup(painel4Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(cancelaBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        painel4Layout.setVerticalGroup(
            painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel4Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saqueBotao)
                    .addComponent(depositoBotao)
                    .addComponent(extBotao))
                .addGap(45, 45, 45)
                .addComponent(alteraBotao)
                .addGap(28, 28, 28)
                .addComponent(cancelaBotao)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        painel3.setLayer(painel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painel3Layout = new javax.swing.GroupLayout(painel3);
        painel3.setLayout(painel3Layout);
        painel3Layout.setHorizontalGroup(
            painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel4)
        );
        painel3Layout.setVerticalGroup(
            painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel4)
        );

        painel2.setLayer(painel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painel2Layout = new javax.swing.GroupLayout(painel2);
        painel2.setLayout(painel2Layout);
        painel2Layout.setHorizontalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel3)
        );
        painel2Layout.setVerticalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel3)
        );

        painel1.setLayer(painel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painel1Layout = new javax.swing.GroupLayout(painel1);
        painel1.setLayout(painel1Layout);
        painel1Layout.setHorizontalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel2)
        );
        painel1Layout.setVerticalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel2)
        );

        javax.swing.GroupLayout container1Layout = new javax.swing.GroupLayout(container1);
        container1.setLayout(container1Layout);
        container1Layout.setHorizontalGroup(
            container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel1)
        );
        container1Layout.setVerticalGroup(
            container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositoBotaoActionPerformed
        Depositar teladep = new Depositar();
        painel2.add(teladep);
        teladep.setVisible(true);
    }//GEN-LAST:event_depositoBotaoActionPerformed

    private void cancelaBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaBotaoActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelaBotaoActionPerformed

    private void saqueBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueBotaoActionPerformed
        Saque telasaque = new Saque();
        painel1.add(telasaque);
        telasaque.setVisible(true);
    }//GEN-LAST:event_saqueBotaoActionPerformed

    private void alteraBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alteraBotaoActionPerformed
        AlteraSenha altsenha = new AlteraSenha();
        painel3.add(altsenha);
        altsenha.setVisible(true);
    }//GEN-LAST:event_alteraBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alteraBotao;
    private javax.swing.JButton cancelaBotao;
    private javax.swing.JPanel container1;
    private javax.swing.JButton depositoBotao;
    private javax.swing.JButton extBotao;
    private javax.swing.JDesktopPane painel1;
    private javax.swing.JDesktopPane painel2;
    private javax.swing.JDesktopPane painel3;
    private javax.swing.JDesktopPane painel4;
    private javax.swing.JButton saqueBotao;
    // End of variables declaration//GEN-END:variables
}
